import AuthService from "./authServices";
import MoiveService from "./movieServices";
import CinemaService from "./cinemaServices";
import Booking from "./bookingServices";
import AdminService from "./adminService";
import BlogsService from "./blogsService";
const movieService = new MoiveService();
const authService = new AuthService();
const cinemaService = new CinemaService();
const bookingService = new Booking();
const adminService = new AdminService();
const blogsService = new BlogsService();
export { blogsService, adminService, movieService, authService, cinemaService, bookingService };
